FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN apt-get update && apt-get install -y \
    docker.io \
    git \
    curl \
    wget \
    openjdk-17-jre \
    && rm -rf /var/lib/apt/lists/*

# Instalar Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# Configurar usuário jenkins
RUN useradd -m -s /bin/bash jenkins
RUN usermod -aG docker jenkins

WORKDIR /app
USER jenkins

CMD ["tail", "-f", "/dev/null"]